// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = express();

app.use(express["static"]('../'));

app.use(express.bodyParser());

app.listen(8008);

console.log('listening...');
